name: Build

on:
  push:
    branches: ['master', 'dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/setup-node@v4
      # - uses: pnpm/action-setup@v4

      - uses: actions/checkout@v4
      - run: git submodule update --init --recursive
      # - run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Get version
        id: version
        uses: ./.github/actions/autoversion

      - run: |
          echo "${{ toJSON(steps.version.outputs) }}"
