name: Build

on:
  push:
    branches: ['master', 'dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/setup-node@v4
      # - uses: pnpm/action-setup@v4

      - uses: actions/checkout@v4
      # - run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - uses: reecetech/version-increment@2024.10.1
        id: version

      - run: |
          echo "${{ toJSON(steps.version.outputs) }}"
